<?php
   $products = $this->getProducts();
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Product</title>
    <style>
    body {
        height: 100vh;
        width: 100vw;
    }

    h3 {
        background-color: black;
        color: wheat;
        text-align: center;
        border-radius: 5px;
    }
    </style>
</head>

<body>
    <div class="container mt-5">
        <h3 class="title mt-2">Product Details</h3>
        <a href="?c=product&a=add"><button type="submit" name="submit" class="btn btn-primary mt-1">Add</button></a>
        <div class="mt-3">

            <table class="table table-hover-table-striped table-bordered mt-2 ">

                <thead>

                    <tr>
                        <th>Product Id</th>
                        <th>Product Name</th>
                        <th>Manufacturer</th>
                        <th>Quantity</th>
                        <th>PKD</th>
                        <th>Status</th>
                        <th>Expiry Date</th>
                        <th>Description</th>
                        <th>Entry date</th>
                        <th>Modify date</th>
                        <th>Action</th>
                    </tr>

                </thead>
                <tbody>

                    <?php  foreach($products as $product){ ?>
                    <tr>
                        
                        <td><?php echo $product->productId; ?></td>
                        <td><?php echo $product->name; ?></td>
                        <td><?php echo $product->manufacturer; ?></td>
                        <td><?php echo $product->quantity; ?></td>
                        <td><?php echo $product->pkd; ?></td>
                        <td><?php echo $product->status; ?></td>
                        <td><?php echo $product->expiryDate; ?></td>
                        <td><?php echo $product->description; ?></td>
                        <td><?php echo $product->createdDate; ?></td>
                        <td><?php echo $product->updatedDate; ?></td>
                        <td><a href="?c=Product&a=edit&id=<?php echo $product->productId; ?>" class="btn btn-primary">Edit</a> 
                        <a href="?c=Product&a=delete&id=<?php echo $product->productId; ?>" class="btn btn-danger mt-1">Delete</a></td>
                    </tr>
                    <?php  }?>
                </tbody>
            </table>
        </div>
       </div>
    </div>
    
</body>
</html>