<?php
Ccc::loadFile("Model/Customer.php");
if( $_GET['id']){ 
    $customer = new Table();
    $query = "SELECT* from `customer` join `address` on customer.customerId = address.customerId where customer.customerId ='$_GET[id]' and address.customerId='$_GET[id]'";
    $result = $customer->fetchAll($query);
}    

 ?>
 
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Add Customer</title>
    <style>
    .container {


        padding: 10px;

    }

    h1 {
        background-color: black;
        color: wheat;
        text-align: center;
        border-radius: 5px;
    }

    hr {
        background-color: black;
    }

    .radio {
        margin: 5px;
    }
    </style>
</head>

<body>
<div class="container mt-5">
        <h1 class="mt-2">Edit Customer Details</h1>
        <div class="personal data mt-3 ">
            <h3>Personal information </h3>
            <form action="" method="post">
                     <?php foreach($result as $data){  }?>
                <div class="row">
                    <div class="form-group col-sm-6">
                        <label for="fname">First name</label>
                        <input type="text" value="<?php echo  $data->firstName; ?>" class="form-control" name="fname" required>
                    </div>
                    <div class="form-group col-sm-6">
                        <label for="lname">Last name</label>
                        <input type="text" class="form-control" value="<?php echo  $data->lastName; ?>" name="lname" required>
                    </div>

                </div>
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" class="form-control" value="<?php echo  $data->email; ?>" name="email" required>
                </div>
                <div class="row">

                    <div class="form-group col-sm-6">
                        <label for="mno">Mobile No</label>
                        <input type="text" class="form-control" value="<?php echo  $data->contact; ?>" name="mno" required>
                    </div>
                    <div class="form-group col-sm-6">
                        <label for="dob">Date of Birth</label>
                        <input type="date" name="dob" value="<?php echo  $data->dateOfBirth; ?>" class="form-control" required>
                    </div>

                </div>
                <div class="form-group col-sm-6 gender">

                    <label for="gender"> Gender </label>
                    <div>

                        Male <input type="radio" name="gender" class="radio" value="male" >
                        Female <input type="radio" name="gender" class="radio" value="female">
                        Other <input type="radio" name="gender" class="radio" value="other">
                    </div>
                </div>






        </div>

        <hr>

        <div class="Address data mt-4 ">
            <h3>Address </h3>
            <form action="">
                <div class="row">

                    <div class="form-group col-sm-6">
                        <label for="Hname">House name</label>
                        <input type="text" class="form-control" value="<?php echo  $data->homeName; ?>" name="hname">
                    </div>
                    <div class="form-group col-sm-6">
                        <label for="street">Street Address</label>
                        <input type="text" class="form-control" value="<?php echo  $data->street; ?>" name="street">
                    </div>

                </div>

                <div class="row">

                    <div class="form-group col-sm-6">
                        <label for="land">Landmark</label>
                        <input type="text" class="form-control" value="<?php echo  $data->landmark; ?>" name="land">
                    </div>
                    <div class="form-group col-sm-6">
                        <label for="city">City</label>
                        <input type="text" name="city" value="<?php echo  $data->city; ?>" class="form-control">
                    </div>

                </div>
                <div class="row">

                    <div class="form-group col-sm-6">
                        <label for="pin">Pin code</label>
                        <input type="number" class="form-control" value="<?php echo  $data->code; ?>" name="pin">
                    </div>
                    <div class="form-group col-sm-6">
                        <label for="state">State</label>
                        <input type="text" name="state" value="<?php echo  $data->state; ?>" class="form-control">
                    </div>

                </div>

        </div>
        <button type="submit" name="submit" class="btn btn-primary mt-1">Update</button>
        <a href="?c=customer&a=grid" name="submit" class="btn btn-success mt-1">Return</a>
 
        </form>
    </div>

     

</body>

</html>